Gene ontology(go) adapter
Habush/biocypher-metta pull request #22
Opened 2024-05-19 10:16 UTC by kedistS

2024-05-20 11:13 UTC, Habush requested changes

2024-05-20 11:13 UTC, Habush commented on biocypher_metta/adapters/gene_ontology_adapter.py
> +    def get_graph(self, ontology='go'):
This method already exists in the parent class and the one in the parent class should be used

2024-05-20 11:13 UTC, Habush commented on biocypher_metta/adapters/gene_ontology_adapter.py
> +    def get_nodes(self):
What's the difference between the `get_nodes` and `get_edges` methods in this class and in the `OntologyAdapter` parent class? I don't see much of a difference. If there is no difference, perhaps no need to override it here.

2024-05-20 11:13 UTC, Habush commented on config/adapters_config.yaml
> +      dry_run: True
`dry_run` should be `False` in the main adapters config. It should be set `True` in the sample adapters config.

2024-05-27 09:24 UTC, Habush requested changes

2024-05-27 09:24 UTC, Habush commented on biocypher_metta/adapters/ontologies_adapter.py
> +        self.graph = self.get_graph()
`get_graph`  is being called without the `ontology`  argument

2024-05-27 09:24 UTC, Habush commented on biocypher_metta/adapters/ontologies_adapter.py
> +        self.graph = self.get_graph()
`get_graph` is being called without the `ontology` argument

2024-05-27 09:24 UTC, Habush commented on biocypher_metta/adapters/ontologies_adapter.py
> +
shouldn't there be a method definition here?

2024-05-27 09:24 UTC, Habush commented on biocypher_metta/adapters/gene_ontology_adapter.py
> +    def get_graph(self, ontology='go'):
I still don't see a reason for this method to exist here. can't you call `self.graph(ontology='go')` when you want the `graph` method in the parent class

2024-05-29 19:02 UTC, kedistS commented on biocypher_metta/adapters/ontologies_adapter.py
> +
Could you please clarify which method you are referring to?

2024-06-03 10:28 UTC, Habush requested changes

2024-06-03 10:28 UTC, Habush commented on biocypher_metta/adapters/gene_ontology_adapter.py
> +    def __init__(self, write_properties, add_provenance, ontology, type, label="ontology term", dry_run=False):
As per the schema, the label name should be `go`

2024-06-03 10:28 UTC, Habush commented on biocypher_metta/adapters/gene_ontology_adapter.py
> +        super().__init__(write_properties, add_provenance, ontology, type, label, dry_run)
Minor but better to pass arguments to the parent class after instantiating the fields of the current class

2024-06-03 10:28 UTC, Habush commented on biocypher_metta/adapters/gene_ontology_adapter.py
> +        self.ONTOLOGIES = {
Where is this field used?

2024-06-03 10:28 UTC, Habush commented on biocypher_metta/adapters/ontologies_adapter.py
> +    def get_graph(self):
This method sets the `self.graph` field and then returns it. But it's unnecessary to return the field after setting it.

2024-06-03 10:28 UTC, Habush commented on biocypher_metta/adapters/ontologies_adapter.py
> +    def get_graph(self):
I'd suggest to change the method's name to `update_graph` and then set the `graph` field in it without returning it. Then on the `get_nodes` method, you'd just call `self.update_graph` and the `self.graph` field now contains the updated ontology graph

2024-06-03 10:28 UTC, Habush commented on biocypher_metta/adapters/ontologies_adapter.py
> +        self.graph = self.get_graph()
Change this to `self.update_graph()`.

2024-06-03 10:28 UTC, Habush commented on biocypher_metta/adapters/ontologies_adapter.py
> +        super().__init__(write_properties, add_provenance)
Minor but better to pass arguments to the parent class after instantiating the fields of the current class

2024-06-03 10:28 UTC, Habush commented on biocypher_metta/adapters/gene_ontology_adapter.py
> +        self.graph = self.get_graph()
`get_graph` is being called in the parent's `get_nodes` method, so why it being called here again?

2024-06-03 10:28 UTC, Habush commented on biocypher_metta/adapters/ontologies_adapter.py
> +        self.graph = self.get_graph()
Change this to `self.update_graph()`.

2024-06-05 11:01 UTC, Habush requested changes

2024-06-05 11:01 UTC, Habush commented on biocypher_metta/adapters/ontologies_adapter.py
> +        return None, None
To indicate this method is abstract, just relapce the `return` statement with `pass`.

2024-06-05 13:15 UTC, Habush approved these changes
Looks good.

2024-06-06 09:41 UTC, merged